VERSION ?= $(shell git describe --tags --always --dirty 2>/dev/null || echo dev)
LDFLAGS := -ldflags "-X main.version=$(VERSION)"

generate:
	go generate ./internal/manpage/

build: generate
	go build $(LDFLAGS) -o sortie ./cmd/sortie

run:
	go run ./cmd/sortie

test:
	go test -v ./...

vet:
	go vet ./...

clean:
	rm -rf dist/
	rm -f sortie

# Pre-flight checks for release. Refuses to proceed with a dirty tree, an
# untagged HEAD, failing tests, missing NOTICES entries, broken man page, or
# AI authorship references in tracked files. Runs after `clean generate` so
# the embedded man page is fresh; the working-tree check then catches any
# uncommitted source changes that would leak into release artifacts.
release-checks:
	@echo "==> [1/6] Working tree is clean"
	@if [ -n "$$(git status --porcelain)" ]; then \
		echo "ERROR: working tree has uncommitted changes:"; \
		git status --short; \
		exit 1; \
	fi
	@echo "==> [2/6] HEAD is at a tag"
	@if ! git describe --exact-match --tags HEAD >/dev/null 2>&1; then \
		echo "ERROR: HEAD is not at a tag. Tag the release first: git tag vX.Y.Z"; \
		exit 1; \
	fi
	@echo "==> [3/6] go vet + go test -race"
	@go vet ./...
	@go test -race ./...
	@echo "==> [4/6] NOTICES covers every runtime dependency"
	@deps=$$(for os in linux darwin windows; do \
		GOOS=$$os go list -deps -f '{{.Module}}' ./cmd/sortie/ 2>/dev/null; \
	done | grep -v '<nil>' | grep -v 'msjurset/sortie' | awk '{print $$1}' | sort -u); \
	for path in $$deps; do \
		if ! grep -qF "$$path" NOTICES; then \
			echo "ERROR: runtime dependency $$path is not in NOTICES"; \
			exit 1; \
		fi; \
	done
	@echo "==> [5/6] Man page parses cleanly"
	@if command -v mandoc >/dev/null 2>&1; then \
		mandoc -W error sortie.1 >/dev/null 2>/tmp/sortie-man-err; \
		rc=$$?; \
		if [ $$rc -ne 0 ]; then \
			echo "ERROR: mandoc found errors in sortie.1:"; \
			cat /tmp/sortie-man-err; \
			rm -f /tmp/sortie-man-err; \
			exit 1; \
		fi; \
		rm -f /tmp/sortie-man-err; \
	elif command -v groff >/dev/null 2>&1; then \
		groff -mandoc -Tutf8 sortie.1 >/dev/null 2>/tmp/sortie-man-err; \
		if [ -s /tmp/sortie-man-err ]; then \
			echo "ERROR: groff produced warnings on sortie.1:"; \
			cat /tmp/sortie-man-err; \
			rm -f /tmp/sortie-man-err; \
			exit 1; \
		fi; \
		rm -f /tmp/sortie-man-err; \
	else \
		echo "  (skipped — neither mandoc nor groff installed)"; \
	fi
	@echo "==> [6/6] No AI authorship references in tracked files"
	@# Character-class wrappers (e.g. c[l]aude) keep this regex from matching
	@# itself when git grep walks the Makefile.
	@if git grep -i -nE "co-authored-by:.*(c[l]aude|a[n]thropic)|generated by (c[l]aude|[a]i|a[n]thropic)" 2>/dev/null | grep -v "^$$"; then \
		echo "ERROR: AI authorship references found in tracked files (see above)"; \
		exit 1; \
	fi
	@echo "==> All release checks passed for $(VERSION)."

# release-tag validates VERSION and tags HEAD if not already tagged. Required
# usage: `make release VERSION=v0.5.1`. Without VERSION, the auto-derived
# `git describe` value falls through and fails the format check.
release-tag:
	@# Allow vX.Y.Z with optional pre-release suffix that starts with a letter
	@# (e.g. v1.2.3-rc1, v1.2.3-beta.2). Reject git-describe output like
	@# v1.2.3-5-gabc1234[-dirty] where the suffix starts with a digit.
	@if ! echo "$(VERSION)" | grep -qE '^v[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z][a-zA-Z0-9._-]*)?$$'; then \
		echo "ERROR: pass VERSION=vX.Y.Z to release. Example:"; \
		echo "  make release VERSION=v0.5.1"; \
		echo "(got '$(VERSION)')"; \
		exit 1; \
	fi
	@if git rev-parse "$(VERSION)" >/dev/null 2>&1; then \
		if [ "$$(git rev-parse $(VERSION)^{commit})" != "$$(git rev-parse HEAD)" ]; then \
			echo "ERROR: tag $(VERSION) already exists at $$(git rev-parse --short $(VERSION)) but HEAD is $$(git rev-parse --short HEAD)"; \
			echo "Either check out the tagged commit, or pick a different VERSION."; \
			exit 1; \
		fi; \
		echo "==> Tag $(VERSION) already at HEAD; reusing."; \
	else \
		echo "==> Tagging $(VERSION) at HEAD..."; \
		git tag -a "$(VERSION)" -m "Release $(VERSION)"; \
	fi

release: release-tag clean generate release-checks
	@echo "==> Cross-compiling release artifacts for $(VERSION)..."
	@mkdir -p dist
	cp sortie.1 dist/
	GOOS=linux   GOARCH=amd64 go build $(LDFLAGS) -o dist/sortie ./cmd/sortie && \
		tar -czf dist/sortie-$(VERSION)-linux-amd64.tar.gz -C dist sortie sortie.1 && rm dist/sortie
	GOOS=linux   GOARCH=arm64 go build $(LDFLAGS) -o dist/sortie ./cmd/sortie && \
		tar -czf dist/sortie-$(VERSION)-linux-arm64.tar.gz -C dist sortie sortie.1 && rm dist/sortie
	GOOS=darwin  GOARCH=amd64 go build $(LDFLAGS) -o dist/sortie ./cmd/sortie && \
		tar -czf dist/sortie-$(VERSION)-darwin-amd64.tar.gz -C dist sortie sortie.1 && rm dist/sortie
	GOOS=darwin  GOARCH=arm64 go build $(LDFLAGS) -o dist/sortie ./cmd/sortie && \
		tar -czf dist/sortie-$(VERSION)-darwin-arm64.tar.gz -C dist sortie sortie.1 && rm dist/sortie
	GOOS=windows GOARCH=amd64 go build $(LDFLAGS) -o dist/sortie.exe ./cmd/sortie && \
		cd dist && zip sortie-$(VERSION)-windows-amd64.zip sortie.exe sortie.1 && rm sortie.exe
	rm dist/sortie.1
	@echo "==> Release artifacts in dist/ for $(VERSION):"
	@ls -1 dist/

deploy: build install-man install-completions
	install -d ~/.local/bin
	install -m 755 sortie ~/.local/bin/sortie

install-man:
	install -d /usr/local/share/man/man1
	install -m 644 sortie.1 /usr/local/share/man/man1/sortie.1

install-completions:
	install -d ~/.oh-my-zsh/custom/completions
	install -m 644 completions/_sortie ~/.oh-my-zsh/custom/completions/_sortie
	@echo "Installed zsh completions"
	@echo "Refreshing zsh completions..."
	@zsh -c 'autoload -U compinit && rm -f ~/.zcompdump* && compinit' 2>/dev/null || true
	@if [ -d /usr/local/share/bash-completion/completions ] || [ -d /opt/homebrew/share/bash-completion/completions ]; then \
		dest=$$([ -d /opt/homebrew/share/bash-completion/completions ] && echo /opt/homebrew/share/bash-completion/completions || echo /usr/local/share/bash-completion/completions); \
		install -m 644 completions/sortie.bash "$$dest/sortie"; \
		echo "Installed bash completions to $$dest/sortie"; \
	else \
		echo "Bash completions directory not found, skipping"; \
	fi

PLIST_DEST := $(HOME)/Library/LaunchAgents/com.msjurset.sortie.plist
BINARY_PATH := $(HOME)/.local/bin/sortie
LOG_PATH := $(HOME)/.config/sortie/logs/sortie.log

install-launchd:
	@if [ -f "$(PLIST_DEST)" ]; then \
		echo "Unloading existing service..."; \
		launchctl unload "$(PLIST_DEST)" 2>/dev/null || true; \
	fi
	@mkdir -p "$(HOME)/Library/LaunchAgents" "$(HOME)/.config/sortie/logs"
	sed -e 's|__BINARY_PATH__|$(BINARY_PATH)|g' -e 's|__LOG_PATH__|$(LOG_PATH)|g' \
		com.msjurset.sortie.plist.tpl > "$(PLIST_DEST)"
	launchctl load "$(PLIST_DEST)"
	@echo "Service installed and started."
	@echo "  Plist: $(PLIST_DEST)"
	@echo "  Log:   $(LOG_PATH)"

uninstall-launchd:
	@if [ -f "$(PLIST_DEST)" ]; then \
		launchctl unload "$(PLIST_DEST)" 2>/dev/null || true; \
		rm -f "$(PLIST_DEST)"; \
		echo "Service uninstalled."; \
	else \
		echo "No service installed."; \
	fi

.PHONY: generate build run test vet clean release release-tag release-checks deploy install-man install-completions install-launchd uninstall-launchd
